import traceback


def print_exception(e):
    traceback.print_exc(e)
